all:
  children:
    fortimanager:
      hosts:
        fmg-demo:
          ansible_host: 198.51.100.80
      vars:
        fmg_api_port: 443
        fmg_user: "{{ lookup('env', 'FMG_USER') | default('apiadmin', true) }}"
        fmg_password: "{{ lookup('env', 'FMG_PASSWORD') | default(omit, true) }}"
        customer_adom: demo-customer
        inet_adom: demo-inet
        workspace_mode: normal
